-- BASIC SALARY TABLE CREATION
-- Run this first if the above doesn't work

-- Just create the basic table
CREATE TABLE public.salaries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    salary_date date NOT NULL,
    amount numeric(10,2) NOT NULL,
    employee_id text,
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Add basic constraint
ALTER TABLE public.salaries 
ADD CONSTRAINT salaries_business_id_not_empty 
CHECK (length(trim(business_id)) > 0);

-- Enable RLS
ALTER TABLE public.salaries ENABLE ROW LEVEL SECURITY;

-- Create basic policies
CREATE POLICY salaries_select_policy ON public.salaries FOR SELECT USING (true);
CREATE POLICY salaries_insert_policy ON public.salaries FOR INSERT WITH CHECK (true);
CREATE POLICY salaries_update_policy ON public.salaries FOR UPDATE USING (true);
CREATE POLICY salaries_delete_policy ON public.salaries FOR DELETE USING (true);

-- Grant permissions
GRANT ALL ON public.salaries TO anon;
GRANT ALL ON public.salaries TO authenticated;

-- Test insert
INSERT INTO public.salaries (business_id, salary_date, amount, employee_id, notes) 
VALUES ('santhosh1', CURRENT_DATE, 1000.00, 'TEST', 'Test entry');

-- Verify
SELECT 'BASIC SALARIES TABLE CREATED' as status;
SELECT COUNT(*) as total_salaries FROM public.salaries;
