-- CREATE SUPPLIERS TABLE
-- This will create the suppliers table that's missing

CREATE TABLE IF NOT EXISTS public.suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id text NOT NULL,
    name text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    UNIQUE (business_id, name)
);

-- Enable RLS
ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;

-- Create policies
DROP POLICY IF EXISTS suppliers_select_policy ON public.suppliers;
DROP POLICY IF EXISTS suppliers_insert_policy ON public.suppliers;
DROP POLICY IF EXISTS suppliers_update_policy ON public.suppliers;
DROP POLICY IF EXISTS suppliers_delete_policy ON public.suppliers;

CREATE POLICY suppliers_select_policy ON public.suppliers FOR SELECT USING (true);
CREATE POLICY suppliers_insert_policy ON public.suppliers FOR INSERT WITH CHECK (true);
CREATE POLICY suppliers_update_policy ON public.suppliers FOR UPDATE USING (true);
CREATE POLICY suppliers_delete_policy ON public.suppliers FOR DELETE USING (true);

-- Grant permissions
GRANT ALL ON public.suppliers TO anon;
GRANT ALL ON public.suppliers TO authenticated;
GRANT USAGE ON SEQUENCE public.suppliers_id_seq TO anon;
GRANT USAGE ON SEQUENCE public.suppliers_id_seq TO authenticated;

-- Insert sample data
INSERT INTO public.suppliers (business_id, name) 
VALUES 
    ('santhosh1', 'Local Supplier 1'),
    ('santhosh1', 'Local Supplier 2'),
    ('vasan', 'Local Supplier 1'),
    ('vasan', 'Local Supplier 2')
ON CONFLICT DO NOTHING;

-- Verify
SELECT 'SUPPLIERS TABLE CREATED SUCCESSFULLY' as status;
SELECT COUNT(*) as total_suppliers FROM public.suppliers;
