-- Suppliers table
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  business_id text not null,
  name text not null,
  created_at timestamp with time zone default now(),
  unique (business_id, name)
);

-- Extend purchases table for detailed tracking
alter table if exists public.purchases
  add column if not exists supplier_id bigint references public.suppliers(id) on delete set null,
  add column if not exists product_id bigint references public.products(id) on delete set null,
  add column if not exists quantity_kg numeric,
  add column if not exists price_per_kg numeric,
  add column if not exists paid_amount numeric;

-- Load entries: link to product and supplier
alter table if exists public.load_entries
  add column if not exists product_id bigint references public.products(id) on delete set null,
  add column if not exists supplier_id bigint references public.suppliers(id) on delete set null;

-- Salaries table
create table if not exists public.salaries (
  id bigint generated by default as identity primary key,
  business_id text not null,
  salary_date date not null,
  amount numeric not null,
  created_at timestamp with time zone default now()
);

-- Basic RLS placeholders (adjust as needed)
alter table public.suppliers enable row level security;
alter table public.purchases enable row level security;
alter table public.load_entries enable row level security;
alter table public.salaries enable row level security;

-- Policies to allow read/write for anon key limited by business_id must exist in app logic
-- You may already have policies; add matching ones for new tables/columns as needed.
